### ISSUE TITLE
Paper-fab broken layout on latest chrome

### ISSUE THREAD

**Issue by jgw96** [PolymerElements/paper-fab#14] opened 2015-06-04 06:47 UTC
Here is my html:

![screenshot 2015-06-04 at 1 45 27 am](https://cloud.githubusercontent.com/assets/8823093/7978487/67ee2a24-0a5b-11e5-9427-66176a8561f7.png)

and here is that html in the browser:
![screenshot 2015-06-04 at 1 44 08 am](https://cloud.githubusercontent.com/assets/8823093/7978493/7a783b9e-0a5b-11e5-8ffd-3cae62ae10af.png)

Chrome dev tools shows no errors and I cant figure out the cause. Also(and i put this in a seperate issue on the paper-header-panel repository) but paper-header-panel is also still broken.

**Comment by jgw96** [comment] 2015-06-04 06:47
and that is using version 1.0.1 paper-fab

**Comment by kasperpeulen** [comment] 2015-06-04 11:51
@jgw96 You are using the old flex layout attributes. You know have to use classe for that.

I think easier for other people if you paste the code, instead of making a screenshot, so that they can try to reproduce.

**Comment by jgw96** [comment] 2015-06-04 15:15
With the exact same html as above but with the flex attributes removed im still running into the exact same issue. should i make a jsbin for it?

**Comment by kasperpeulen** [comment] 2015-06-04 15:24
That would help :)

**Comment by jgw96** [comment] 2015-06-04 15:44
So with my exact html just copy and pasted over from my editor and placed in a plunkr it works perfectly fine.
http://plnkr.co/edit/KC9Asq6EfpJuy2muzDSH?p=preview

**Comment by jgw96** [comment] 2015-06-04 15:44
Thanks by the way.

**Comment by jgw96** [comment] 2015-06-04 15:44
It must be my version of the elements that im using? although there all at the latest version.

**Comment by kasperpeulen** [comment] 2015-06-04 15:52
@jgw96 I guess it must have to do something with the imports indeed.

**Comment by notwaldorf** [comment] 2015-06-17 22:49
Closing this, since `paper-fab` is working as expected :)

**Closed by notwaldorf** 2015-06-17 22:49 UTC
