### ISSUE TITLE
[1.0] Paper-fab warns of missing `undefined` icon set.

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-fab#9] opened 2015-05-21 23:46 UTC
<link rel="import" href="bower_components/iron-icons/iron-icons.html">
    <link rel="import" href="bower_components/paper-fab/paper-fab.html">

    <paper-fab icon="favorite"></paper-fab>

![screen shot 2015-05-21 at 4 44 43 pm](https://cloud.githubusercontent.com/assets/238208/7761288/df062e8c-ffd8-11e4-99d7-00e4758d7861.png)

**Comment by robdodson** [comment] 2015-05-26 16:07
@cdata @notwaldorf any updates on this?

**Comment by cdata** [comment] 2015-05-26 16:34
I will address this today, sorry for the delay.

**Comment by notwaldorf** [comment] 2015-06-19 20:37
Duplicate of https://github.com/PolymerElements/iron-icons/issues/18

**Closed by notwaldorf** 2015-06-19 20:37 UTC
Labels: duplicate
