### ISSUE TITLE
Unable to load element from unpkg.com

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/paper-fab#93] opened 2019-02-04 15:41 UTC
I am migrating to lit because next month chrome stops html import

But looking at the amount of broken modules it seems polymer team jumped of the titanic and left us on the ship that will hit the iceberg in march

example

https://unpkg.com/@polymer/paper-fab/paper-fab.js?module

redirect broken

**Comment by TimvdLippe** [comment] 2019-02-04 18:17
I am unable to reproduce this issue. The redirect is working for me.

**Comment by keanulee** [comment] 2019-02-04 18:38
Update - appears to load (though very slowly) now (green bar/TTFB is 20s):
![image](https://user-images.githubusercontent.com/1319720/52229134-01e56a00-2869-11e9-9f30-9ad0e5a5d6ad.png)

**Comment by gertcuykens** [comment] 2019-02-05 02:53
Ok thanks for confirmation. No go in Belgium, it get stuck at
![image](https://user-images.githubusercontent.com/863731/52250475-73b8c480-28f8-11e9-86dd-524bcf0e3493.png)

But that's not polymers fault, nevertheless I am pretty sure not all elements are lit ready yet.

Example 
https://jsbin.com/fafexes/edit?html,console,output

https://github.com/PolymerElements/paper-input/issues/687

**Comment by TimvdLippe** [comment] 2019-02-05 11:59
`paper-input` is working for me as well. I am closing this as duplicate of https://github.com/unpkg/unpkg.com/issues/177 This is not an issue with Polymer, but with unpkg.

**Closed by TimvdLippe** 2019-02-05 11:59 UTC
